---
---  create table CCO_POSTING_PROCESS in SPRIT
---

CREATE TABLE CCO_POSTING_PROCESS ( 
  CCO_PROCESS_ID     NUMBER           NOT NULL,
  RELEASE_NUMBER_ID  NUMBER           NOT NULL, 
  IMAGE_NAME         VARCHAR2 (64)    NOT NULL, 
  FTP_LOG            VARCHAR2 (2500)  NULL,
  POSTING_STATUS     CHAR(1)          NULL,
  CREATED_DATE       DATE             NOT NULL,  
  CREATED_BY         VARCHAR(8)       NOT NULL,
  ADM_COMMENTS       VARCHAR(50)      NULL
  );

DROP SEQUENCE CCO_POSTING_PROCESS_SEQ; 
  
CREATE SEQUENCE CCO_POSTING_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

GRANT ALL ON CCO_POSTING_PROCESS_SEQ TO SHR_RDA;

GRANT ALL ON CCO_POSTING_PROCESS  TO SHR_RDA;


---
---  run following SQL under SHR_RDA
---

CREATE OR REPLACE SYNONYM CCO_POSTING_PROCESS_SEQ FOR SPRIT.CCO_POSTING_PROCESS_SEQ;

CREATE OR REPLACE SYNONYM CCO_POSTING_PROCESS FOR SPRIT.CCO_POSTING_PROCESS;


---
--- run following SQL under SHR_RDA
---

alter table SHR_IMAGE add (
  IS_POSTED_TO_CCO char(1), 
  CCO_POSTED_TIME date,
  IMAGE_SIZE_COMPRESSED number,
  IMAGE_SIZE_UNCOMPRESSED number,
  MD5CHKSUM Varchar2(32),
  CCO_POSTED_BY VARCHAR2 (8)
  );

