--Copyright (c) 2009 by Cisco Systems, Inc.
/*
 	Current Release - Sprit 7.5 
 	Created by - holchen
 	Created date - Feb 17, 2009
        Updated by - aselvara@cisco.com,updated Date March 15,2009
        Run on SHR_RDA schema
*/
 DROP TABLE CSPR_SW_RETIREMENT_RELEASE;
 
 DROP SEQUENCE CSPR_SW_RETIREMENT_RELEASE_SEQ;
 
 CREATE SEQUENCE CSPR_SW_RETIREMENT_RELEASE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;

 CREATE TABLE CSPR_SW_RETIREMENT_RELEASE(
   SW_RETIREMENT_RELEASE_ID     NUMBER                  NOT NULL,
   RELEASE_NUMBER_ID            NUMBER                NOT NULL,
   MIGRATION_PATH               VARCHAR2(100 BYTE),       
   TARGET_MIGRATION_DATE        DATE,                     
   CREATED_BY                   VARCHAR2(8 BYTE)          NOT NULL,
   CREATED_DATE                 DATE                      NOT NULL,
   ADM_USERID                   VARCHAR2(8 BYTE)          NOT NULL,
   ADM_TIMESTAMP                DATE                      NOT NULL,
   ADM_FLAG                     CHAR(1 BYTE)              NOT NULL,
   ADM_COMMENT                  VARCHAR2(50 BYTE)
 );  
 
 
 ALTER TABLE CSPR_SW_RETIREMENT_RELEASE
 ADD CONSTRAINT PK_CSPR_SW_RETIREMENT_RELEASE
 PRIMARY KEY(SW_RETIREMENT_RELEASE_ID);
 
 
 ALTER TABLE CSPR_SW_RETIREMENT_RELEASE ADD(
 CONSTRAINT FK_SW_RETIRE_REL_NUMBER_ID
 FOREIGN KEY (RELEASE_NUMBER_ID) 
 REFERENCES SHR_RELEASE_NUMBER (RELEASE_NUMBER_ID));

 CREATE unique INDEX IDX_SW_RET_RELEASE_NUMBER_ID
 on CSPR_SW_RETIREMENT_RELEASE(RELEASE_NUMBER_ID);
  
  
 GRANT ALL ON CSPR_SW_RETIREMENT_RELEASE TO SHR_RDA;
  
 GRANT ALL ON CSPR_SW_RETIREMENT_RELEASE_SEQ TO SHR_RDA;
 

 DROP TABLE CSPR_SW_RETIREMENT_IMAGE;

 DROP SEQUENCE CSPR_SW_RETIREMENT_IMAGE_SEQ;

 CREATE SEQUENCE CSPR_SW_RETIREMENT_IMAGE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
  
 CREATE TABLE CSPR_SW_RETIREMENT_IMAGE(
   SW_RETIREMENT_IMAGE_ID                    NUMBER NOT NULL,
   RELEASE_NUMBER_ID                         NUMBER,
   IMAGE_ID                                  NUMBER NOT NULL,
   MIGRATION_RELEASE_NUMBER_ID               NUMBER,
   MIGRATION_PATH                            VARCHAR2(200),
   TARGET_MIGRATION_DATE                     DATE,
   SOFTWARE_TYPE_MDF_ID                      NUMBER,-- change this to  MDF_SWT_CONCEPT_ID later
   DEPLOYMENT_STATUS_ID                      NUMBER,
   STATUS                                    VARCHAR2(20),
   SUBMIT_EMAIL_NOTIFICATION                 VARCHAR2(1),
   EXECUTE_EMAIL_NOTIFICATION                VARCHAR2(1),
   CREATED_BY                                VARCHAR2(8) NOT NULL,
   CREATED_DATE                              DATE NOT NULL,
   ADM_USERID                                VARCHAR2(8) NOT NULL,
   ADM_TIMESTAMP                             DATE NOT NULL,
   ADM_FLAG                                  CHAR(1) NOT NULL,
   ADM_COMMENT                               VARCHAR2(50)
 );

  ALTER TABLE CSPR_SW_RETIREMENT_IMAGE
  ADD CONSTRAINT PK_CSPR_SW_RETIREMENT_IMAGE
  PRIMARY KEY(SW_RETIREMENT_IMAGE_ID);
  
 
  ALTER TABLE CSPR_SW_RETIREMENT_IMAGE ADD(
  CONSTRAINT FK_SW_RETIRE_REL_IMAGE_ID
  FOREIGN KEY (IMAGE_ID) 
  REFERENCES SHR_IMAGE (IMAGE_ID));
  
  
 ALTER TABLE CSPR_SW_RETIREMENT_IMAGE ADD (
 CONSTRAINT FK_SW_RETIRE_MDF_CONCEPT_ID
 FOREIGN KEY (SOFTWARE_TYPE_MDF_ID) 
 REFERENCES SHR_mdf_swtype_attr (MDF_SWT_CONCEPT_ID));

 CREATE INDEX IDX_SW_RET_IRELEASE_NUMBER_ID
 on CSPR_SW_RETIREMENT_IMAGE(RELEASE_NUMBER_ID);

 CREATE unique INDEX IDX_SW_RET_IMAGE
 on CSPR_SW_RETIREMENT_IMAGE(IMAGE_ID);
   
 GRANT ALL ON CSPR_SW_RETIREMENT_IMAGE TO SHR_RDA;
 
 GRANT ALL ON CSPR_SW_RETIREMENT_IMAGE_SEQ TO SHR_RDA;
 
 
 DROP TABLE CSPR_SW_RETIREMENT_COMMENTS;

 DROP SEQUENCE CSPR_SW_RETIRE_COMMENTS_SEQ;

 CREATE SEQUENCE CSPR_SW_RETIRE_COMMENTS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
      
 CREATE TABLE CSPR_SW_RETIREMENT_COMMENTS(
        SW_RETIREMENT_COMMENTS_ID   NUMBER                  NOT NULL,
        COMMENT_DETAIL         VARCHAR2(500 BYTE),
        RELEASE_NUMBER_ID         NUMBER                    NOT NULL,
        CREATED_BY                VARCHAR2(8 BYTE)          NOT NULL,
        CREATED_DATE              DATE                      NOT NULL,
        ADM_USERID                VARCHAR2(8 BYTE)          NOT NULL,
        ADM_TIMESTAMP             DATE                      NOT NULL,
        ADM_FLAG                  CHAR(1 BYTE)              NOT NULL,
        ADM_COMMENT               VARCHAR2(50 BYTE)
  );  


  ALTER TABLE CSPR_SW_RETIREMENT_COMMENTS
  ADD CONSTRAINT PK_CSPR_SW_RETIREMENT_COMMENTS
  PRIMARY KEY(SW_RETIREMENT_COMMENTS_ID);
    
  ALTER TABLE CSPR_SW_RETIREMENT_COMMENTS ADD(
  CONSTRAINT FK_SW_RETIRE_REL_COMMENTS
  FOREIGN KEY (RELEASE_NUMBER_ID) 
  REFERENCES SHR_RELEASE_NUMBER(RELEASE_NUMBER_ID));

  CREATE INDEX IDX_SW_RET_CRELEASE_NUMBER_ID
  on CSPR_SW_RETIREMENT_COMMENTS(RELEASE_NUMBER_ID);

       
 GRANT ALL ON CSPR_SW_RETIREMENT_COMMENTS TO SHR_RDA;
       
 GRANT ALL ON CSPR_SW_RETIRE_COMMENTS_SEQ TO SHR_RDA;



DROP TABLE CSPR_TEMPLATE;

DROP SEQUENCE CSPR_TEMPLATE_SEQ;

CREATE SEQUENCE CSPR_TEMPLATE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE; 

CREATE TABLE CSPR_TEMPLATE
( TEMPLATE_ID       NUMBER NOT NULL,
  TEMPLATE_NAME     VARCHAR2(100) NOT NULL,
  TEMPLATE_CONTENT  CLOB NOT NULL,
  CREATED_BY                VARCHAR2(8 BYTE)          NOT NULL,
  CREATED_DATE              DATE                      NOT NULL,
  ADM_USERID                VARCHAR2(8 BYTE)          NOT NULL,
  ADM_TIMESTAMP             DATE                      NOT NULL,
  ADM_FLAG                  CHAR(1 BYTE)              NOT NULL,
  ADM_COMMENT               VARCHAR2(50 BYTE)
);

  ALTER TABLE CSPR_TEMPLATE
  ADD CONSTRAINT PK_CSPR_TEMPLATE
  PRIMARY KEY(TEMPLATE_ID);

  CREATE INDEX IDX_TEMPLATE_NAME
  on CSPR_TEMPLATE(TEMPLATE_NAME);

grant all on CSPR_TEMPLATE to shr_rda;
