/**************************************************
Copyright (c) 2007 by Cisco Systems, Inc.

Created for CSCsg06391 fix. 

Author: Kelly H. (kellmill)
Date  : 02/15/2007
**************************************************/

DROP TABLE CSPR_RELEASE_CCO_POST CASCADE CONSTRAINTS;

DROP SEQUENCE CSPR_RELEASE_CCO_POST_SEQ; 

CREATE TABLE CSPR_RELEASE_CCO_POST (
CSPR_RELEASE_CCO_POST_ID NUMBER        NOT NULL,
RELEASE_NUMBER_ID        NUMBER        NOT NULL,
INTGR_ENGR               VARCHAR (35)  NULL,
RELEASE_NOTES            VARCHAR (200) NOT NULL,
SOFTWARE_ADVISORY        VARCHAR (35)  NOT NULL,
COMMENTS                 VARCHAR (200) NULL,
CREATED_BY               VARCHAR2 (8)  NOT NULL,
CREATED_DATE             DATE          NOT NULL,
ADM_USERID               VARCHAR2 (8)  NOT NULL,
ADM_TIMESTAMP            DATE          NOT NULL,
ADM_FLAG                 CHAR (1)      NOT NULL,
ADM_COMMENT              VARCHAR2 (50) NULL
);

alter table CSPR_RELEASE_CCO_POST
add CONSTRAINT FK_RELEASE_NUMBER_ID
FOREIGN KEY ( RELEASE_NUMBER_ID )
REFERENCES SHR_RELEASE_NUMBER( RELEASE_NUMBER_ID );

alter table CSPR_RELEASE_CCO_POST
add CONSTRAINT PK_CSPR_RELEASE_CCO_POST
PRIMARY KEY ( CSPR_RELEASE_CCO_POST_ID );

CREATE SEQUENCE CSPR_RELEASE_CCO_POST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

