--Copyright (c) 2007 by Cisco Systems, Inc. -kdharmal

DROP SEQUENCE SHR_RDA.SHR_RELEASE_MDF_SEQ;
CREATE SEQUENCE SHR_RDA.SHR_RELEASE_MDF_SEQ
START WITH 1
MAXVALUE 9999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

DROP TABLE SHR_RELEASE_NUMBER_MDF CASCADE CONSTRAINTS;
CREATE TABLE SHR_RELEASE_NUMBER_MDF ( 
  RELEASE_NUMBER_MDF_ID       NUMBER        NOT NULL, 
  RELEASE_NUMBER_ID           NUMBER        NOT NULL, 
  MDF_CONCEPT_ID              NUMBER        NOT NULL, 
  CREATED_BY                  VARCHAR2 (8)  NOT NULL, 
  CREATED_DATE                DATE          NOT NULL, 
  ADM_USERID                  VARCHAR2 (8)  NOT NULL, 
  ADM_TIMESTAMP               DATE          NOT NULL, 
  ADM_FLAG                    CHAR (1)      NOT NULL, 
  ADM_COMMENT                 VARCHAR2 (50))
