--Copyright (c) 2007 by Cisco Systems, Inc.

CREATE TABLE OUTAGE_CATEGORY (
	OUTAGE_CATEGORY_ID		NUMBER			NOT NULL,
	OUTAGE_CATEGORY_NAME	VARCHAR2(50)	NOT NULL,
	OUTAGE_CATEGORY_DESCRIPTION VARCHAR2(256),
	CREATED_BY VARCHAR2(8) NOT NULL,
	CREATED_DATE DATE NOT NULL,
	ADM_USERID	VARCHAR2(8) NOT NULL,
	ADM_TIMESTAMP DATE NOT NULL,
	ADM_FLAG	CHAR(1) NOT NULL,
	ADM_COMMENT VARCHAR2(50)	
);

CREATE TABLE OUTAGE (
	OUTAGE_ID	NUMBER	NOT NULL,
	OUTAGE_CATEGORY_ID	NUMBER	NOT NULL,
	START_DATE_TIME	DATE	NOT NULL,
	END_DATE_TIME	DATE	NOT NULL,
	IS_ENABLED		CHAR(1) DEFAULT 'Y', 
	OUTAGE_MESSAGE	VARCHAR2(1000),
	CREATED_BY VARCHAR2(8) NOT NULL,
	CREATED_DATE DATE NOT NULL,
	ADM_USERID	VARCHAR2(8) NOT NULL,
	ADM_TIMESTAMP DATE NOT NULL,
	ADM_FLAG	CHAR(1) NOT NULL,
	ADM_COMMENT VARCHAR2(50)
);

CREATE SEQUENCE OUTAGE_CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE OUTAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

ALTER TABLE OUTAGE_CATEGORY
ADD CONSTRAINT PK_OUTAGE_CATEGORY
PRIMARY KEY (OUTAGE_CATEGORY_ID);
 
ALTER TABLE OUTAGE
ADD CONSTRAINT PK_OUTAGE
PRIMARY KEY (OUTAGE_ID);

ALTER TABLE OUTAGE
ADD ( CONSTRAINT FK_OUTAGE_CATEGORY
      FOREIGN KEY (OUTAGE_CATEGORY_ID) 
   REFERENCES OUTAGE_CATEGORY );
   
 ALTER TABLE OUTAGE
	ADD CONSTRAINT UK_OUTAGE
	UNIQUE (OUTAGE_CATEGORY_ID, START_DATE_TIME,END_DATE_TIME); 
	 