--Copyright (c) 2009 by Cisco Systems, Inc.
/*
 	Current Release - Sprit 7.5 
 	Created by - holchen
 	Created date - Feb 23, 2009
        Updated by - aselvara@cisco.com,updated Date March 15,2009
        Run on SHR_RDA schema
 */
CREATE OR REPLACE SYNONYM CSPR_SW_RETIREMENT_RELEASE FOR SPRIT.CSPR_SW_RETIREMENT_RELEASE;
CREATE OR REPLACE SYNONYM CSPR_SW_RETIREMENT_RELEASE_SEQ FOR SPRIT.CSPR_SW_RETIREMENT_RELEASE_SEQ;
CREATE OR REPLACE SYNONYM CSPR_SW_RETIREMENT_IMAGE FOR SPRIT.CSPR_SW_RETIREMENT_IMAGE;
CREATE OR REPLACE SYNONYM CSPR_SW_RETIREMENT_IMAGE_SEQ FOR SPRIT.CSPR_SW_RETIREMENT_IMAGE_SEQ;
CREATE OR REPLACE SYNONYM CSPR_SW_RETIREMENT_COMMENTS FOR SPRIT.CSPR_SW_RETIREMENT_COMMENTS; 
CREATE OR REPLACE SYNONYM CSPR_SW_RETIRE_COMMENTS_SEQ FOR SPRIT.CSPR_SW_RETIRE_COMMENTS_SEQ;
CREATE OR REPLACE SYNONYM CSPR_TEMPLATE FOR SPRIT.CSPR_TEMPLATE;
CREATE OR REPLACE SYNONYM CSPR_TEMPLATE_SEQ FOR SPRIT.CSPR_TEMPLATE_SEQ;
