/********************************************
1. CSPR_RELEASE_NUMBER
********************************************/

DROP TABLE CSPR_RELEASE_NUMBER CASCADE CONSTRAINTS;

CREATE TABLE CSPR_RELEASE_NUMBER(
RELEASE_NUMBER_ID    NUMBER         NOT NULL,
MAJOR_RELEASE        VARCHAR2 (20)      NULL,
MAINTENANCE_RELEASE  VARCHAR2 (20)      NULL,
MINOR_RELEASE        VARCHAR2 (20)      NULL,
RELEASE_NAME         VARCHAR2 (20)  NOT NULL, 
OS_TYPE_ID           NUMBER         NOT NULL, 
CREATED_BY           VARCHAR2 (8)    NOT NULL, 
CREATED_DATE         DATE           NOT NULL, 
ADM_USERID           VARCHAR2 (8)   NOT NULL, 
ADM_TIMESTAMP        DATE           NOT NULL, 
ADM_FLAG             CHAR (1)       NOT NULL, 
ADM_COMMENT          VARCHAR2 (50)      NULL
);

ALTER TABLE CSPR_RELEASE_NUMBER
ADD CONSTRAINT UK_CSPR_RELEASE_NUMBER
UNIQUE (RELEASE_NAME);

ALTER TABLE CSPR_RELEASE_NUMBER
ADD ( CONSTRAINT PK_CSPR_RELEASE_NUMBER_ID
      PRIMARY KEY( RELEASE_NUMBER_ID) ) ;


/********************************************
2. CSPR_MACHINE_OS_TYPE
********************************************/

DROP SEQUENCE CSPR_MACHINE_OS_TYPE_SEQ;

DROP TABLE CSPR_MACHINE_OS_TYPE CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_MACHINE_OS_TYPE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_MACHINE_OS_TYPE(
MACHINE_OS_TYPE_ID    NUMBER         NOT NULL,
MACHINE_OS_TYPE_NAME  VARCHAR2(50)   NOT NULL,
MACHINE_OS_TYPE_DESC  VARCHAR2(100)      NULL,
CREATED_BY            VARCHAR2 (8)   NOT NULL, 
CREATED_DATE          DATE           NOT NULL, 
ADM_USERID            VARCHAR2 (8)   NOT NULL, 
ADM_TIMESTAMP         DATE           NOT NULL, 
ADM_FLAG              CHAR (1)       NOT NULL, 
ADM_COMMENT           VARCHAR2 (50)      NULL
);

ALTER TABLE CSPR_MACHINE_OS_TYPE
ADD CONSTRAINT UK_CSPR_MACHINE_OS_TYPE
UNIQUE (MACHINE_OS_TYPE_NAME);

ALTER TABLE CSPR_MACHINE_OS_TYPE
ADD ( CONSTRAINT PK_CSPR_MACHINE_OS_TYPE_ID
      PRIMARY KEY( MACHINE_OS_TYPE_ID) ) ;

/********************************************
3. CSPR_CDC_ACCESS_LEVEL
********************************************/

DROP SEQUENCE CSPR_CDC_ACCESS_LEVEL_SEQ;

DROP TABLE CSPR_CDC_ACCESS_LEVEL CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_CDC_ACCESS_LEVEL_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_CDC_ACCESS_LEVEL(
CDC_ACCESS_LEVEL_ID    NUMBER         NOT NULL,
CDC_ACCESS_LEVEL_NAME  VARCHAR2(50)   NOT NULL,
CDC_ACCESS_LEVEL_DESC  VARCHAR2(100)      NULL,
CREATED_BY             VARCHAR2 (8)   NOT NULL, 
CREATED_DATE           DATE           NOT NULL, 
ADM_USERID             VARCHAR2 (8)   NOT NULL, 
ADM_TIMESTAMP          DATE           NOT NULL, 
ADM_FLAG               CHAR (1)       NOT NULL, 
ADM_COMMENT            VARCHAR2 (50)      NULL
);

ALTER TABLE CSPR_CDC_ACCESS_LEVEL
ADD CONSTRAINT UK_CSPR_CDC_ACCESS_LEVEL
UNIQUE (CDC_ACCESS_LEVEL_NAME);

ALTER TABLE CSPR_CDC_ACCESS_LEVEL
ADD ( CONSTRAINT PK_CSPR_CDC_ACCESS_LEVEL_ID
      PRIMARY KEY( CDC_ACCESS_LEVEL_ID) ) ;

/********************************************
4. CSPR_IMAGE
********************************************/

DROP SEQUENCE CSPR_IMAGE_SEQ;

DROP TABLE CSPR_IMAGE CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_IMAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_IMAGE (
IMAGE_ID                  NUMBER         NOT NULL,
RELEASE_NUMBER_ID         NUMBER         NOT NULL,
IMAGE_NAME                VARCHAR2(64)   NOT NULL, 
IMAGE_DESCRIPTION         VARCHAR2(500)  NOT NULL, 
IS_SOFTWARE_ADVISORY      CHAR(1)        NOT NULL,
SOFTWARE_ADVISORY_ID      VARCHAR2(20)       NULL,
IS_DEFERRED 	          CHAR(1)        NOT NULL,
DEFERRAL_ID               VARCHAR2(20)       NULL,
SOFTWARE_ADVISORY_DOC_URL VARCHAR2 (200)     NULL,
DEFERRAL_ADVISORY_DOC_URL VARCHAR2 (200)     NULL,
IS_CRYPTO    		  CHAR(1)        NOT NULL,
MEMORY       		  NUMBER             NULL,
RELEASE_DOC_URL   	  VARCHAR2 (200)     NULL,
INSTALLATION_DOC_URL      VARCHAR2 (200)     NULL,
PRODUCT_CODE              VARCHAR2 (18)      NULL,
MACHINE_OS_TYPE_ID        NUMBER             NULL,
SOURCE_LOCATION           VARCHAR2 (200)     NULL,
CDC_ACCESS_LEVEL_ID       NUMBER         NOT NULL,
POSTING_TYPE_ID           NUMBER             NULL,
IS_POSTED_TO_CCO          CHAR (1)           NULL, 
CCO_POSTED_TIME           DATE               NULL, 
CCO_POSTED_BY             VARCHAR2 (8)       NULL, 
CREATED_BY                VARCHAR2 (8)   NOT NULL, 
CREATED_DATE              DATE           NOT NULL, 
ADM_USERID                VARCHAR2 (8)   NOT NULL, 
ADM_TIMESTAMP             DATE           NOT NULL, 
ADM_FLAG                  CHAR (1)       NOT NULL, 
ADM_COMMENT               VARCHAR2 (50)      NULL
);

ALTER TABLE CSPR_IMAGE
ADD CONSTRAINT UK_CSPR_IMAGE
UNIQUE (IMAGE_NAME);

ALTER TABLE CSPR_IMAGE
ADD ( CONSTRAINT PK_CSPR_IMAGE_ID
      PRIMARY KEY( IMAGE_ID) ) ;

ALTER TABLE CSPR_IMAGE
ADD  ( CONSTRAINT FK_IMAGE_RELEASE_NUMBER
       FOREIGN KEY (RELEASE_NUMBER_ID)
       REFERENCES CSPR_RELEASE_NUMBER ) ;

ALTER TABLE CSPR_IMAGE
ADD  ( CONSTRAINT FK_IMAGE_MACHINE_OS_TYPE_ID
       FOREIGN KEY (MACHINE_OS_TYPE_ID)
       REFERENCES CSPR_MACHINE_OS_TYPE ) ;

/********************************************
5. CSPR_IMAGE_MDF
********************************************/

DROP SEQUENCE CSPR_IMAGE_MDF_SEQ;

DROP TABLE CSPR_IMAGE_MDF CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_IMAGE_MDF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_IMAGE_MDF (
IMAGE_MDF_ID              NUMBER         NOT NULL,
IMAGE_ID                  NUMBER         NOT NULL,
MDF_ID                    NUMBER         NOT NULL,
CREATED_BY                VARCHAR2 (8)   NOT NULL, 
CREATED_DATE              DATE           NOT NULL, 
ADM_USERID                VARCHAR2 (8)   NOT NULL, 
ADM_TIMESTAMP             DATE           NOT NULL, 
ADM_FLAG                  CHAR (1)       NOT NULL, 
ADM_COMMENT               VARCHAR2 (50)      NULL
);

ALTER TABLE CSPR_IMAGE_MDF
ADD CONSTRAINT UK_CSPR_IMAGE_MDF
UNIQUE (IMAGE_ID,MDF_ID);

ALTER TABLE CSPR_IMAGE_MDF
ADD ( CONSTRAINT PK_CSPR_IMAGE_MDF_ID
      PRIMARY KEY( IMAGE_MDF_ID) ) ;

ALTER TABLE CSPR_IMAGE_MDF
ADD  ( CONSTRAINT FK_IMAGE_MDF_ID
       FOREIGN KEY (MDF_ID)
       REFERENCES CSPR_CISCO_MDF_PRODUCT ) ;

ALTER TABLE CSPR_IMAGE_MDF
ADD  ( CONSTRAINT FK_MDF_IMAGE_ID
       FOREIGN KEY (IMAGE_ID)
       REFERENCES CSPR_IMAGE ) ;

/********************************************
6. CSPR_METADATA
********************************************/

DROP SEQUENCE CSPR_METADATA_SEQ;

DROP TABLE CSPR_METADATA CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_METADATA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_METADATA(
METADATA_ID               NUMBER        NOT NULL,
METADATA_NAME             VARCHAR2(50)  NOT NULL,
METADATA_UI_LABEL         VARCHAR2(75)  NOT NULL,
METADATA_DESC        VARCHAR2(200)     NULL,                   
IS_CCO_REQUIRED           CHAR(1)       NOT NULL,
CREATED_BY                VARCHAR2 (8)  NOT NULL, 
CREATED_DATE              DATE          NOT NULL, 
ADM_USERID                VARCHAR2 (8)  NOT NULL, 
ADM_TIMESTAMP             DATE          NOT NULL, 
ADM_FLAG                  CHAR (1)      NOT NULL, 
ADM_COMMENT               VARCHAR2 (50)     NULL
);

ALTER TABLE CSPR_METADATA
ADD CONSTRAINT UK_CSPR_METADATA
UNIQUE (METADATA_NAME);

ALTER TABLE CSPR_METADATA
ADD ( CONSTRAINT PK_CSPR_METADATA_ID
      PRIMARY KEY( METADATA_ID) ) ;

/********************************************
7. CSPR_SOFTWARE_METADATA
********************************************/

DROP SEQUENCE CSPR_SOFTWARE_METADATA_SEQ;

DROP TABLE CSPR_SOFTWARE_METADATA CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_SOFTWARE_METADATA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_SOFTWARE_METADATA(
SOFTWARE_METADATA_ID      NUMBER        NOT NULL,
OS_TYPE_ID                NUMBER        NOT NULL,
METADATA_ID               NUMBER        NOT NULL,
IS_BU_REQUIRED            CHAR(1)       NOT NULL,
CREATED_BY                VARCHAR2 (8)  NOT NULL, 
CREATED_DATE              DATE          NOT NULL, 
ADM_USERID                VARCHAR2 (8)  NOT NULL, 
ADM_TIMESTAMP             DATE          NOT NULL, 
ADM_FLAG                  CHAR (1)      NOT NULL, 
ADM_COMMENT               VARCHAR2 (50)     NULL
);

ALTER TABLE CSPR_SOFTWARE_METADATA
ADD CONSTRAINT UK_CSPR_SOFTWARE_METADATA
UNIQUE (OS_TYPE_ID,METADATA_ID);

ALTER TABLE CSPR_SOFTWARE_METADATA
ADD ( CONSTRAINT PK_CSPR_SOFTWARE_METADATA_ID
      PRIMARY KEY( SOFTWARE_METADATA_ID) ) ;

ALTER TABLE CSPR_SOFTWARE_METADATA
ADD  ( CONSTRAINT FK_SOFTWARE_METADATA_OS_TYPE
       FOREIGN KEY (OS_TYPE_ID)
       REFERENCES SHR_OS_TYPE ) ;

ALTER TABLE CSPR_SOFTWARE_METADATA
ADD  ( CONSTRAINT FK_SOFTWARE_METADATA_ID
       FOREIGN KEY (METADATA_ID)
       REFERENCES CSPR_METADATA ) ;

/********************************************
8. SHR_PLATFORM_MDF
********************************************/

DROP SEQUENCE SHR_PLATFORM_MDF_SEQ;

DROP TABLE SHR_PLATFORM_MDF CASCADE CONSTRAINTS;

CREATE SEQUENCE SHR_PLATFORM_MDF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE TABLE SHR_PLATFORM_MDF(
PLATFORM_MDF_ID           NUMBER        NOT NULL,
INDIVIDUAL_PLATFORM_ID    NUMBER        NOT NULL,
MDF_ID                    NUMBER        NOT NULL,
CREATED_BY                VARCHAR2(8)   NOT NULL, 
CREATED_DATE              DATE          NOT NULL, 
ADM_USERID                VARCHAR2(8)   NOT NULL, 
ADM_TIMESTAMP             DATE          NOT NULL, 
ADM_FLAG                  CHAR (1)      NOT NULL, 
ADM_COMMENT               VARCHAR2 (50)     NULL
);

ALTER TABLE SHR_PLATFORM_MDF
ADD CONSTRAINT UK_SHR_PLATFORM_MDF
UNIQUE (INDIVIDUAL_PLATFORM_ID,MDF_ID);

ALTER TABLE SHR_PLATFORM_MDF
ADD ( CONSTRAINT PK_SHR_PLATFORM_MDF
      PRIMARY KEY( PLATFORM_MDF_ID) ) ;

ALTER TABLE SHR_PLATFORM_MDF
ADD  ( CONSTRAINT FK_SHR_INDIVIDUAL_PLATFORM_ID
       FOREIGN KEY (INDIVIDUAL_PLATFORM_ID)
       REFERENCES SHR_INDIVIDUAL_PLATFORM ) ;

/********************************************
9. CSPR_SOFTWARE_PM
********************************************/

DROP SEQUENCE CSPR_SOFTWARE_TYPE_PM_SEQ;

DROP TABLE CSPR_SOFTWARE_TYPE_PM CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_SOFTWARE_TYPE_PM_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE TABLE CSPR_SOFTWARE_TYPE_PM(
SOFTWARE_TYPE_PM_ID        NUMBER NOT          NULL,
USER_ID                    VARCHAR2(8)     NOT NULL,
CREATED_BY                 VARCHAR2(8)     NOT NULL, 
CREATED_DATE               DATE            NOT NULL, 
ADM_USERID                 VARCHAR2(8)     NOT NULL, 
ADM_TIMESTAMP              DATE            NOT NULL, 
ADM_FLAG                   CHAR (1)        NOT NULL, 
ADM_COMMENT                VARCHAR2 (50)       NULL
);

ALTER TABLE CSPR_SOFTWARE_TYPE_PM
ADD CONSTRAINT UK_SOFTWARE_TYPE_USER_ID
UNIQUE (USER_ID);

ALTER TABLE CSPR_SOFTWARE_TYPE_PM
ADD ( CONSTRAINT PK_SOFTWARE_TYPE_PM_ID
      PRIMARY KEY( SOFTWARE_TYPE_PM_ID) ) ;
/************************************************
 10. CSPR_PRODUCTS_ATTR 
********************************************/
DROP SEQUENCE CSPR_PRODUCT_ATTR_SEQ;

DROP TABLE CSPR_PRODUCT_ATTR CONSTRAINTS;

CREATE SEQUENCE CSPR_PRODUCT_ATTR_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;

 CREATE TABLE CSPR_PRODUCTS_ATTR (
  MDF_CONCEPT_ID           NUMBER(38)           NOT NULL,
  MDF_CONCEPT_NAME         VARCHAR2(640)        NOT NULL,
  MDF_PARENT_CONCEPT_ID    NUMBER(38)               NULL,
  MDF_PARENT_CONCEPT_NAME  VARCHAR2(4000)           NULL,
  LIFECYCLE                VARCHAR2(4000)           NULL,
  INTERNAL_LAUNCH_DATE     VARCHAR2(4000)           NULL,
  EXTERNAL_LAUNCH_DATE     VARCHAR2(4000)           NULL,
  EOL_DATE                 VARCHAR2(4000)           NULL,
  LAST_DATE_OF_SUPPORT     VARCHAR2(4000)           NULL,
  OBSOLETE_DATE            VARCHAR2(4000)           NULL,
  METACLASS                VARCHAR2(4000)           NULL,
  LAST_MODIFIED_DATE       DATE                     NULL
);

ALTER TABLE CSPR_PRODUCTS_ATTR 
ADD CONSTRAINT PK_CSPR_PRODUCTS_ATTR 
PRIMARY KEY (MDF_CONCEPT_ID);


CREATE INDEX IX_CSPR_PRODUCTS_ATTR_PID 
ON CSPR_PRODUCTS_ATTR(MDF_PARENT_CONCEPT_ID);

/***********************************************
  11. CSPR_SECONDARY_PARENT_RELS
***********************************************/
DROP SEQUENCE CSPR_SECONDARY_PARENT_RELS_SEQ;

DROP TABLE CSPR_SECONDARY_PARENT_RELS CONSTRAINTS;

CREATE SEQUENCE CSPR_SECONDARY_PARENT_RELS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CSPR_SECONDARY_PARENT_RELS(
  MDF_CONCEPT_ID         NUMBER(10),
  MDF_CONCEPT_NAME       VARCHAR2(640),
  SECONDARY_PARENT_ID    NUMBER(10),
  SECONDARY_PARENT_NAME  VARCHAR2(640),
  LAST_MODIFIED_DATE     DATE
);

CREATE INDEX IX_CSPR_2ND_PARENT_RELS_MDFID 
ON CSPR_SECONDARY_PARENT_RELS (MDF_CONCEPT_ID);

CREATE INDEX IX_CSPR_2ND_PARENT_RELS_PID 
ON CSPR_SECONDARY_PARENT_RELS(SECONDARY_PARENT_ID);


/*========================================
 OLD structure:
10. CSPR_CISCO_MDF_PRODUCT
DROP SEQUENCE CSPR_CISCO_MDF_PRODUCT_SEQ;

DROP TABLE CSPR_CISCO_MDF_PRODUCT CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_CISCO_MDF_PRODUCT_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE TABLE  CSPR_CISCO_MDF_PRODUCT (
  MDF_ID                   NUMBER          NOT NULL,
  MDF_NAME                 VARCHAR2(50)    NOT NULL,
  MDF_DESC            VARCHAR2(100)            NULL,
  META_CLASS               VARCHAR2(25)    NOT NULL,
  CREATED_BY               VARCHAR2(8)     NOT NULL, 
  CREATED_DATE             DATE            NOT NULL,  
  ADM_USERID               VARCHAR2(8)     NOT NULL, 
  ADM_TIMESTAMP            DATE            NOT NULL, 
  ADM_FLAG                 CHAR (1)        NOT NULL, 
  ADM_COMMENT              VARCHAR2 (50)       NULL
);

ALTER TABLE CSPR_CISCO_MDF_PRODUCT
ADD CONSTRAINT UK_CISCO_MDF_NAME
UNIQUE (MDF_NAME);

ALTER TABLE CSPR_CISCO_MDF_PRODUCT
ADD ( CONSTRAINT PK_CISCP_MDF_PRODUCT
      PRIMARY KEY( MDF_ID) ) ;

/********************************************
11. CSPR_CISCO_MDF_HIERARCHY
********************************************/

DROP SEQUENCE CSPR_CISCO_MDF_HIERARCHY_SEQ;

DROP TABLE CSPR_CISCO_MDF_HIERARCHY CASCADE CONSTRAINTS;

CREATE SEQUENCE CSPR_CISCO_MDF_HIERARCHY_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CSPR_CISCO_MDF_HIERARCHY(
  MDF_ID                   NUMBER          NOT NULL,
  PARENT_MDF_ID            NUMBER              NULL,
  CREATED_BY               VARCHAR2(8)     NOT NULL, 
  CREATED_DATE             DATE            NOT NULL,  
  ADM_USERID               VARCHAR2(8)     NOT NULL, 
  ADM_TIMESTAMP            DATE            NOT NULL, 
  ADM_FLAG                 CHAR (1)        NOT NULL, 
  ADM_COMMENT              VARCHAR2 (50)       NULL
);

ALTER TABLE CSPR_CISCO_MDF_HIERARCHY
ADD ( CONSTRAINT PK_CISCO_MDF_HIERARCHY
PRIMARY KEY( MDF_ID) ) ;

========================================*/

/*===========================================
* 12. 

 CSPR_YPUBLISH_XML_LOG

 TRANSACTION_ID
 METADATA_XML
 YPUBLISH_XML_RESPONSE
 IS_YPUBLISH_ACCEPTED
 NO_OF_ATTEMPT
 CREATED_BY
 CREATED_DATE
 ADM_USERID
 ADM_TIMESTAMP
 ADM_FLAG
 ADM_COMMENT

======================================================
/*===========================================
* 13

 CSPR_YPUBLISH_IMAGE_LOG

 TRANSACTION_ID
 RELEASE_NUMBER_ID
 IMAGE_ID
 YPUBLISH_STATUS_CODE
 YPUBLISH_STATUS_LOG
 IS_PUBLISHED
 CREATED_BY
 CREATED_DATE
 ADM_USERID
 ADM_TIMESTAMP
 ADM_FLAG
 ADM_COMMENT

======================================================


