-- Copyright (c) 2007-2008 by Cisco Systems, Inc.
/*
 	Current Release - IOSXE 
 	Last updated by - rakkamat
 	Last updated date - Dec, 20 2007 
 */
 
 DROP TABLE	CSPR_MASTER_OS_TYPE;
 
 DROP SEQUENCE CSPR_MASTER_OS_TYPE_SEQ;
 
 CREATE TABLE CSPR_MASTER_OS_TYPE(
 	MASTER_OS_TYPE_ID		NUMBER 			NOT NULL,
 	MASTER_OS_TYPE_NAME		VARCHAR2(30)	NOT NULL,
    CREATED_BY            VARCHAR2(8 BYTE)         NOT NULL,
    CREATED_DATE          DATE                     NOT NULL,
    ADM_USERID            VARCHAR2(8 BYTE)         NOT NULL,
    ADM_TIMESTAMP         DATE                     NOT NULL,
    ADM_FLAG              CHAR(1 BYTE)             NOT NULL,
    ADM_COMMENT           VARCHAR2(50 BYTE)
 );
 
 -- Primary Key --
 ALTER TABLE CSPR_MASTER_OS_TYPE
 ADD CONSTRAINT PK_MASTER_OS_TYPE_ID
 PRIMARY KEY(MASTER_OS_TYPE_ID);

CREATE SEQUENCE CSPR_MASTER_OS_TYPE_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
 
GRANT ALL ON CSPR_MASTER_OS_TYPE TO SHR_RDA;
  
GRANT ALL ON CSPR_MASTER_OS_TYPE_SEQ TO SHR_RDA;	