--Copyright (c) 2007 by Cisco Systems, Inc.

CREATE TABLE CSPR_RELEASE_PLATFORM_MDF
(
  CSPR_RELEASE_PLATFORM_MDF_ID  INTEGER         NOT NULL,
  RELEASE_NUMBER_ID             INTEGER         NOT NULL,
  PLATFORM_ID                   INTEGER         NOT NULL,
  MDF_CONCEPT_ID                INTEGER         NOT NULL,
  IS_GOING_TO_CCO               CHAR            NOT NULL,
  CREATED_BY                    VARCHAR2(8 BYTE) NOT NULL,
  CREATED_DATE                  DATE            NOT NULL,
  ADM_USERID                    VARCHAR2(8 BYTE) NOT NULL,
  ADM_TIMESTAMP                 DATE            NOT NULL,
  ADM_FLAG                      CHAR(1 BYTE)    NOT NULL,
  ADM_COMMENT                   VARCHAR2(50 BYTE)
);

CREATE SEQUENCE CSPR_RELEASE_PLATFORM_MDF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

ALTER TABLE CSPR_RELEASE_PLATFORM_MDF 
ADD CONSTRAINT PK_CSPR_REL_PFM_MDF_ID
PRIMARY KEY(CSPR_RELEASE_PLATFORM_MDF_ID);

ALTER TABLE CSPR_RELEASE_PLATFORM_MDF
ADD (CONSTRAINT UK_CSPR_RELEASE_PLATFORM_MDF
	UNIQUE(RELEASE_NUMBER_ID,PLATFORM_ID,MDF_CONCEPT_ID));

GRANT ALL ON CSPR_RELEASE_PLATFORM_MDF TO SHR_RDA;
 
GRANT ALL ON CSPR_RELEASE_PLATFORM_MDF_SEQ TO SHR_RDA;

