--Copyright (c) 2007 by Cisco Systems, Inc.
/*
 	Current Release - Sprit 6.10 
 	Last updated by - holchen
 	Last updated date - Nov 6, 2007 
 */
 
 DROP TABLE CSPR_LATEST_RELEASE_OPTOUT;
 
 DROP SEQUENCE CSPR_LATEST_RELEASE_OPTOUT_SEQ;
 
 CREATE TABLE CSPR_LATEST_RELEASE_OPTOUT(
   OPTOUT_ID	 	 NUMBER            	  NOT NULL,
   SOFTWARE_TYPE_MDF_ID  NUMBER          	  NOT NULL,
   LAST_GROUP_NAME       VARCHAR2(20 BYTE)        NOT NULL,
   LAST_GROUP_VALUE      VARCHAR2(20 BYTE)        NOT NULL,
   MDF_CONCEPT_ID	 NUMBER(38),
   CREATED_BY            VARCHAR2(8 BYTE)         NOT NULL,
   CREATED_DATE          DATE                     NOT NULL,
   ADM_USERID            VARCHAR2(8 BYTE)         NOT NULL,
   ADM_TIMESTAMP         DATE                     NOT NULL,
   ADM_FLAG              CHAR(1 BYTE)             NOT NULL,
   ADM_COMMENT           VARCHAR2(50 BYTE)
 );  
 
 
 ALTER TABLE CSPR_LATEST_RELEASE_OPTOUT
 ADD CONSTRAINT PK_LAST_RELEASE_OPTOUT
 PRIMARY KEY(OPTOUT_ID);
 
 
 ALTER TABLE CSPR_LATEST_RELEASE_OPTOUT ADD(
 CONSTRAINT FK_LAT_REL_OPT_MDF_SWTYPE_ATTR
 FOREIGN KEY (SOFTWARE_TYPE_MDF_ID) 
 REFERENCES SHR_MDF_SWTYPE_ATTR (MDF_SWT_CONCEPT_ID));
 
 
  
 CREATE SEQUENCE CSPR_LATEST_RELEASE_OPTOUT_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
  
 GRANT ALL ON CSPR_LATEST_RELEASE_OPTOUT TO SHR_RDA;
  
 GRANT ALL ON CSPR_LATEST_RELEASE_OPTOUT_SEQ TO SHR_RDA;
