--Copyright (c) 2007 by Cisco Systems, Inc.
CREATE OR REPLACE SYNONYM AUTO_PUBLISH_RELEASE_QUEUE FOR SPRIT.AUTO_PUBLISH_RELEASE_QUEUE;
CREATE OR REPLACE SYNONYM AUTO_PUBLISH_RELEASE_QUEUE_SEQ FOR SPRIT.AUTO_PUBLISH_RELEASE_QUEUE_SEQ;
CREATE OR REPLACE SYNONYM AUTO_PUBLISH_IMAGE_QUEUE FOR SPRIT.AUTO_PUBLISH_IMAGE_QUEUE;

