--Copyright (c) 2007 by Cisco Systems, Inc.
/*
 	Current Release - Sprit 6.10 
 	Last updated by - holchen
 	Last updated date - Nov 6, 2007 
 */
CREATE OR REPLACE SYNONYM CSPR_LATEST_RELEASE_OPTOUT FOR SPRIT.CSPR_LATEST_RELEASE_OPTOUT;
CREATE OR REPLACE SYNONYM CSPR_LATEST_RELEASE_OPTOUT_SEQ FOR SPRIT.CSPR_LATEST_RELEASE_OPTOUT_SEQ;