--Copyright (c) 2008 by Cisco Systems, Inc.
/*
        Current Release - Sprit 6.10.1 
        Last updated by - cchebrol
        Last updated date - Jan 15, 2008 
 */
 
DROP TABLE SPRIT.CSPR_DOC_DETAILS CASCADE CONSTRAINTS;
 
DROP SEQUENCE CSPR_DOC_DETAILS_SEQ;

-- Create CSPR_DOC_DETAILS
CREATE TABLE SPRIT.CSPR_DOC_DETAILS
(
  CSPR_DOC_ID                  NUMBER           NOT NULL,
  SOURCE_LOCATION              VARCHAR2(1000 BYTE) NOT NULL,
  DOC_LAST_MODIFIED_DATE_TIME  DATE             NOT NULL,
  OS_TYPE                      VARCHAR2(128 BYTE) DEFAULT 'IOS' NOT NULL,
  STATUS                       VARCHAR2(20 BYTE) NOT NULL,
  URL                          VARCHAR2(1000 BYTE),
  FTP_RETRY_COUNT              NUMBER,
  AVAILABLE_RETRY_COUNT        NUMBER,
  AVAILABLE_DATE_TIME          DATE,
  FAILURE_MESSAGE              VARCHAR2(500),
  CREATED_BY                   VARCHAR2(8),
  CREATED_DATE                 DATE,
  ADM_FLAG                     CHAR(1),
  ADM_USERID                   VARCHAR2(8),
  ADM_TIMESTAMP                DATE,
  ADM_COMMENT                  VARCHAR2(50)
);

ALTER TABLE SPRIT.CSPR_DOC_DETAILS ADD (
  CONSTRAINT CSPR_DOC_DETAILS_PK
 PRIMARY KEY
 (CSPR_DOC_ID));

CREATE SEQUENCE CSPR_DOC_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

GRANT ALL ON CSPR_DOC_DETAILS TO SHR_RDA;

GRANT ALL ON CSPR_DOC_DETAILS_SEQ TO SHR_RDA;

DROP TABLE SPRIT.CSPR_DOC_PUBLISH CASCADE CONSTRAINTS;
 
DROP SEQUENCE CSPR_DOC_PUBLISH_SEQ;

-- Create CSPR_DOC_PUBLISH Transaction table
CREATE TABLE SPRIT.CSPR_DOC_PUBLISH
(
  CSPR_DOC_PUBLISH_ID  NUMBER                   NOT NULL,
  RELEASE_NUMBER_ID    NUMBER,
  IMAGE_ID             NUMBER,
  CSPR_DOC_ID          NUMBER                   NOT NULL,
  TRANSACTION_ID       NUMBER                   NOT NULL,
  OS_TYPE              VARCHAR2(128 BYTE),
  CREATED_BY           VARCHAR2(8),
  CREATED_DATE         DATE,
  ADM_FLAG             CHAR(1),
  ADM_USERID           VARCHAR2(8),
  ADM_TIMESTAMP        DATE,
  ADM_COMMENT          VARCHAR2(50)
);



ALTER TABLE SPRIT.CSPR_DOC_PUBLISH ADD (
  CONSTRAINT CSPR_DOC_PUBLISH_PK
 PRIMARY KEY
 (CSPR_DOC_PUBLISH_ID));

ALTER TABLE SPRIT.CSPR_DOC_PUBLISH ADD (
  CONSTRAINT CSPR_DOC_PUBLISH_DOC_ID_FK 
 FOREIGN KEY (CSPR_DOC_ID) 
 REFERENCES SPRIT.CSPR_DOC_DETAILS (CSPR_DOC_ID),
  CONSTRAINT CSPR_DOC_PUBLISH_TRANS_ID_FK 
 FOREIGN KEY (TRANSACTION_ID) 
 REFERENCES SPRIT.CSPR_YPUBLISH_TRANS_LOG (TRANSACTION_ID));

CREATE SEQUENCE CSPR_DOC_PUBLISH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

GRANT ALL ON CSPR_DOC_PUBLISH TO SHR_RDA;

GRANT ALL ON CSPR_DOC_PUBLISH_SEQ TO SHR_RDA;
