--Copyright (c) 2007 by Cisco Systems, Inc.

DROP TABLE AUTO_PUBLISH_RELEASE_QUEUE;

CREATE TABLE AUTO_PUBLISH_RELEASE_QUEUE  (
  RELEASE_QUEUE_ID        INTEGER,
  RELEASE_NUMBER_ID       INTEGER NOT NULL,
  RELEASE_NUMBER          VARCHAR2(32 BYTE),
  OS_TYPE_ID              INTEGER NOT NULL,
  TRANSACTION_ID          INTEGER,
  PRED_TRANSACTION_ID     INTEGER,
  CCO_TRANSACTION_TYPE    VARCHAR2(10 BYTE) NOT NULL,
  CCO_TRANSACTION_STATUS  VARCHAR2(10 BYTE),
  NO_OF_ATTEMPTS          INTEGER,
  NEXT_POSTING_TIME       DATE,
  ERROR_MESSAGE           VARCHAR2(2000 BYTE),
  IS_POPULATED            CHAR(1 BYTE),
  IS_METADATA_CHECK_DONE            CHAR(1 BYTE),
  CREATED_BY              VARCHAR2(8 BYTE),
  CREATED_DATE            DATE,
  ADM_USERID              VARCHAR2(8 BYTE),
  ADM_TIMESTAMP           DATE,
  ADM_FLAG                CHAR(1 BYTE),
  ADM_COMMENT             VARCHAR2(200 BYTE)
);

ALTER TABLE AUTO_PUBLISH_RELEASE_QUEUE
ADD CONSTRAINT PK_RELEASE_QUEUE_ID
PRIMARY KEY(RELEASE_QUEUE_ID);

DROP SEQUENCE AUTO_PUBLISH_RELEASE_QUEUE_SEQ;

CREATE SEQUENCE AUTO_PUBLISH_RELEASE_QUEUE_SEQ; 

GRANT ALL ON AUTO_PUBLISH_RELEASE_QUEUE TO SHR_RDA;

GRANT ALL ON AUTO_PUBLISH_RELEASE_QUEUE_SEQ TO SHR_RDA;

DROP TABLE AUTO_PUBLISH_IMAGE_QUEUE;

CREATE TABLE AUTO_PUBLISH_IMAGE_QUEUE  (
  RELEASE_QUEUE_ID        INTEGER,
  IMAGE_ID                INTEGER,
  IMAGE_NAME              VARCHAR2(60 BYTE),
  CREATED_BY              VARCHAR2(8 BYTE),
  CREATED_DATE            DATE,
  ADM_USERID              VARCHAR2(8 BYTE),
  ADM_TIMESTAMP           DATE,
  ADM_FLAG                CHAR(1 BYTE),
  ADM_COMMENT             VARCHAR2(200 BYTE)
);

ALTER TABLE AUTO_PUBLISH_IMAGE_QUEUE  
ADD CONSTRAINT UK_AUTO_PUBLISH_IMAGE_QUEUE
UNIQUE(RELEASE_QUEUE_ID, IMAGE_ID);

GRANT ALL ON AUTO_PUBLISH_IMAGE_QUEUE TO SHR_RDA;

