--Copyright (c) 2006-2007 by Cisco Systems, Inc.

create or replace synonym CCO_HISTORY   for SPRIT_TEST.CCO_HISTORY;
create or replace synonym DEM_MFG_COMPONENT_PARTNO   for SPRIT_TEST.DEM_MFG_COMPONENT_PARTNO;
create or replace synonym DEM_MFG_COMPONENT_PARTNO_SEQ   for SPRIT_TEST.DEM_MFG_COMPONENT_PARTNO_SEQ;
create or replace synonym DEM_MFG_LABEL   for SPRIT_TEST.DEM_MFG_LABEL;
create or replace synonym DEM_MFG_LABEL_SEQ   for SPRIT_TEST.DEM_MFG_LABEL_SEQ;
create or replace synonym DEM_MFG_PLATFORM_LABEL   for SPRIT_TEST.DEM_MFG_PLATFORM_LABEL;
create or replace synonym DEM_MFG_PLATFORM_LABEL_SEQ   for SPRIT_TEST.DEM_MFG_PLATFORM_LABEL_SEQ;
create or replace synonym DEM_MFG_RELEASE_TO_SPEC   for SPRIT_TEST.DEM_MFG_RELEASE_TO_SPEC;
create or replace synonym ENCRYPTION   for SPRIT_TEST.ENCRYPTION;
create or replace synonym GLOBALVAR   for SPRIT_TEST.GLOBALVAR;
create or replace synonym IMAGEBUILD   for SPRIT_TEST.IMAGEBUILD;
create or replace synonym IMAGE_SIZE_UPDATE   for SPRIT_TEST.IMAGE_SIZE_UPDATE;
create or replace synonym IMAGE_SIZE_UPDATE_SEQ   for SPRIT_TEST.IMAGE_SIZE_UPDATE_SEQ;
create or replace synonym IOX_CCO   for SPRIT_TEST.IOX_CCO;
create or replace synonym IOX_CCO_ENTRY_ID_SEQ   for SPRIT_TEST.IOX_CCO_ENTRY_ID_SEQ;
create or replace synonym IOX_HISTORY   for SPRIT_TEST.IOX_HISTORY;
create or replace synonym IOX_OPUS   for SPRIT_TEST.IOX_OPUS;
create or replace synonym IOX_OPUS_ENTRY_ID_SEQ   for SPRIT_TEST.IOX_OPUS_ENTRY_ID_SEQ;
create or replace synonym IOX_OPUS_HISTORY   for SPRIT_TEST.IOX_OPUS_HISTORY;
create or replace synonym MFG_CACHE_BOM   for SPRIT_TEST.MFG_CACHE_BOM;
create or replace synonym MFG_CACHE_HISTORY   for SPRIT_TEST.MFG_CACHE_HISTORY;
create or replace synonym MFG_CACHE_OPUS   for SPRIT_TEST.MFG_CACHE_OPUS;
create or replace synonym MFG_CACHE_PCODE_SEQ   for SPRIT_TEST.MFG_CACHE_PCODE_SEQ;
create or replace synonym MFG_HISTORY   for SPRIT_TEST.MFG_HISTORY;
create or replace synonym PRICE_CACHE_STATUS   for SPRIT_TEST.PRICE_CACHE_STATUS;
create or replace synonym PRICE_ERP_CACHE1   for SPRIT_TEST.PRICE_ERP_CACHE1;
create or replace synonym PRICE_ERP_CACHE2   for SPRIT_TEST.PRICE_ERP_CACHE2;
create or replace synonym PRICE_ERP_VIEW_TABLE   for SPRIT_TEST.PRICE_ERP_VIEW_TABLE;
create or replace synonym PRICE_OPUS_CACHE1   for SPRIT_TEST.PRICE_OPUS_CACHE1;
create or replace synonym PRICE_OPUS_CACHE2   for SPRIT_TEST.PRICE_OPUS_CACHE2;
create or replace synonym PRICE_OPUS_VIEW_TABLE   for SPRIT_TEST.PRICE_OPUS_VIEW_TABLE;
create or replace synonym SPRIT_ROLES   for SPRIT_TEST.SPRIT_ROLES;
create or replace synonym SPRIT_ROLES_SEQ   for SPRIT_TEST.SPRIT_ROLES_SEQ;
create or replace synonym SPRIT_EMAIL_ALIAS for SPRIT_TEST.SPRIT_EMAIL_ALIAS;
create or replace synonym SPRIT_EMAIL_ALIAS_SEQ for SPRIT_TEST.SPRIT_EMAIL_ALIAS_SEQ;
create or replace synonym CSPR_RELEASE_CCO_POST for SPRIT_TEST.CSPR_RELEASE_CCO_POST;
create or replace synonym CSPR_RELEASE_CCO_POST_SEQ for SPRIT_TEST.CSPR_RELEASE_CCO_POST_SEQ;


