--Copyright (c) 2006-2007 by Cisco Systems, Inc.

Grant all on   CCOHISTORY to   SIIS_BUILD ;
Grant all on   CCO_HISTORY to   SHR_RDA ;
Grant all on   DEM_MFG_COMPONENT_PARTNO to   SHR_RDA ;
Grant all on   DEM_MFG_COMPONENT_PARTNO_SEQ to   SHR_RDA ;
Grant all on   DEM_MFG_LABEL to   SHR_RDA ;
Grant all on   DEM_MFG_LABEL_SEQ to   SHR_RDA ;
Grant all on   DEM_MFG_PLATFORM_LABEL to   SHR_RDA ;
Grant all on   DEM_MFG_PLATFORM_LABEL_SEQ to   SHR_RDA ;
Grant all on   DEM_MFG_RELEASE_TO_SPEC to   SHR_RDA ;
Grant all on   ENCRYPTION to   SHR_RDA ;
Grant select on   ENCRYPTION to   SIIS_BUILD ;
Grant all on   GLOBALVAR to   SHR_RDA ;
Grant select on   GLOBALVAR to   SIIS_BUILD ;
Grant all on   IMAGEBUILD to   SHR_RDA WITH GRANT OPTION;
Grant all on   IMAGEBUILD to   SIIS_BUILD ;
Grant update (status,last_updated_date) on IMAGE_SIZE_UPDATE to MFG_CACHE;
Grant all on   IMAGE_SIZE_UPDATE to   SHR_RDA ;
Grant all on   IMAGE_SIZE_UPDATE_SEQ to   SHR_RDA ;
Grant all on   IOX_CCO to   SHR_RDA WITH GRANT OPTION;
Grant all on   IOX_CCO to   SIIS_USER ;
Grant all on   IOX_CCO_ENTRY_ID_SEQ to   SHR_RDA ;
Grant all on   IOX_CCO_ENTRY_ID_SEQ to   SIIS_USER ;
Grant all on   IOX_HISTORY to   SHR_RDA ;
Grant all on   IOX_OPUS to   SHR_RDA WITH GRANT OPTION;
Grant all on   IOX_OPUS to   SIIS_USER ;
Grant all on   IOX_OPUS_ENTRY_ID_SEQ to   SHR_RDA ;
Grant all on   IOX_OPUS_ENTRY_ID_SEQ to   SIIS_USER ;
Grant select,update (process_status,process_date) on MFG_CACHE_BOM to MFG_CACHE;
Grant all on   MFG_CACHE_BOM to   SHR_RDA ;
Grant select on   MFG_CACHE_BOM to   SIIS_BUILD ;
Grant all on   MFG_CACHE_HISTORY to   SHR_RDA ;
Grant all on   MFG_CACHE_HISTORY to   SIIS_BUILD ;
Grant select on   MFG_CACHE_OPUS to   DEFTRACKER ;
Grant select,update (process_status,process_date) on MFG_CACHE_OPUS to MFG_CACHE;
Grant all on   MFG_CACHE_OPUS to   SHR_RDA WITH GRANT OPTION;
Grant select on   MFG_CACHE_OPUS to   SIIS_BUILD ;
Grant all on   MFG_CACHE_PCODE_SEQ to   SHR_RDA ;
Grant all on   MFG_HISTORY to   SHR_RDA ;
Grant all on   MFG_HISTORY to   SIIS_BUILD ;
Grant all on   PRICE_CACHE_STATUS to   SHR_RDA ;
Grant all on   PRICE_CACHE_STATUS to   SIIS_BUILD ;
Grant all on   PRICE_ERP_VALID_CACHE to   SHR_RDA ;
Grant all on   PRICE_ERP_VIEW_TABLE to   SHR_RDA ;
Grant select on   PRICE_ERP_VIEW_TABLE to   SIIS_BUILD ;
Grant all on   PRICE_OPUS_VALID_CACHE to   SHR_RDA ;
Grant all on   PRICE_OPUS_VIEW_TABLE to   SHR_RDA ;
Grant all on   SPRIT_ROLES to   SHR_RDA ;
Grant all on   SPRIT_ROLES_SEQ to   SHR_RDA ;
Grant all on   SPRIT_EMAIL_ALIAS to SHR_RDA ;
Grant all on   SPRIT_EMAIL_ALIAS_SEQ to SHR_RDA ;
Grant all on   CSPR_RELEASE_CCO_POST to SHR_RDA ;
Grant all on   CSPR_RELEASE_CCO_POST_SEQ to SHR_RDA ;
Grant all on  cspr_sw_prioritization          to   shr_rda;
Grant all on  cspr_sw_prioritization_seq      to   shr_rda;
Grant all on  cspr_sw_prioritization_details   to   shr_rda;
Grant all on  cspr_sw_prioritization_d_seq    to   shr_rda;
 
 
