/*
    Copyright (c) 2008 by Cisco Systems, Inc.
    updated by holchen
*/
CREATE OR REPLACE VIEW VW_CSPR_SWTYPE_RELEASE_SORT
(OS_TYPE_ID, MDF_SWT_CONCEPT_ID, MDF_SWT_CONCEPT_NAME, RELEASE_COMPONENT_COLUMN, RELEASE_COMPONENT_NAME, 
 RELEASE_COMPONENT_LABEL, RELEASE_COMPONENT_SEQ, RELEASE_COMPONENT_SEQ_2, RELEASE_COMPONENT_GROUP, IS_REQUIRED, 
 DATA_TYPE, NO_OF_LATEST_RELEASES, PRIMARY_SORT_FIELD, PRIMARY_SORTING_ORDER, SECONDARY_SORT_FIELD, 
 SECONDARY_SORTING_ORDER)
AS 
select som.os_type_id
,smsa.MDF_SWT_CONCEPT_ID
,MDF_SWT_CONCEPT_NAME,
RELEASE_COMPONENT_COLUMN     
,RELEASE_COMPONENT_NAME       
,RELEASE_COMPONENT_LABEL      
,RELEASE_COMPONENT_SEQ        
,RELEASE_COMPONENT_SEQ_2
,RELEASE_COMPONENT_GROUP      
,IS_REQUIRED                  
,DATA_TYPE
,no_of_latest_releases
,PRIMARY_SORT_FIELD  
,PRIMARY_SORTING_ORDER
,SECONDARY_SORT_FIELD
,SECONDARY_SORTING_ORDER
from  SHR_MDF_SWTYPE_ATTR   smsa
     ,shr_ostype_mdfswtype   som
 --  ,shr_software_type_mdf  sstm
 ,CSPR_SWTYPE_RELEASE_COMPONENT csrc
where smsa.MDF_SWT_CONCEPT_ID=som.MDF_SWT_CONCEPT_ID
--and som.MDF_SWT_CONCEPT_ID=sstm.mdf_concept_id
and som.os_type_id=csrc.os_type_id
and som.adm_flag='V'
union
select som.os_type_id
,smsa.MDF_SWT_CONCEPT_ID
,MDF_SWT_CONCEPT_NAME
,'CCO_FCS_DATE' RELEASE_COMPONENT_COLUMN     
,'ReleasePublishDate' RELEASE_COMPONENT_NAME       
,'CCO_FCS_DATE' RELEASE_COMPONENT_LABEL      
,1          RELEASE_COMPONENT_SEQ
,1 RELEASE_COMPONENT_SEQ_2        
,'FALSE'     RELEASE_COMPONENT_GROUP      
,'Y'        IS_REQUIRED                  
,'Date'     DATA_TYPE
,no_of_latest_releases
,PRIMARY_SORT_FIELD  
,PRIMARY_SORTING_ORDER
,SECONDARY_SORT_FIELD
,SECONDARY_SORTING_ORDER
from  SHR_MDF_SWTYPE_ATTR   smsa
     ,shr_ostype_mdfswtype   som
where smsa.MDF_SWT_CONCEPT_ID=som.MDF_SWT_CONCEPT_ID
and os_type_id not in(select os_type_id from CSPR_SWTYPE_RELEASE_COMPONENT)
/

